### ISSUE TITLE
playlist error

### ISSUE THREAD

**Issue by solidvegetal** [FThompson/NetflixController#1]
When one episode ends and goes to the next one, it throws the following error:

> An error occurred: Cannot read property 'parentElement' of undefined. You may need to refresh the page.

tested on a new chrome profile with only extension enabled

**Comment by FThompson** [comment]
Thanks for letting me know! Netflix might have updated their code.

I'll check this out later today and follow up.

**Comment by FThompson** [comment]
Fixed in NetflixController v1.0.2, which is pending publish currently.

Notably the next episode action doesn't work (#4) but at least the extension won't throw an error at the end of episodes anymore.
