### ISSUE TITLE
controller not detected

### ISSUE THREAD

**Issue by KillerWolf1805** [FThompson/NetflixController#12]
invalid value used as weak map key

**Comment by FThompson** [comment]
Hey, thanks for reporting this. I took a look and it should be an easy fix--it appears that the styling library broke. I'll fix it soon (within a day or so).

**Comment by FThompson** [comment]
I've submitted the fix to the Chrome Web Store and the update is pending review. It usually takes between an hour and a day for Google to review and publish the new version (v1.0.4). I'll comment here again when the update is available.

**Comment by FThompson** [comment]
v1.0.4 is live on the Chrome web store. Thanks again!

**Comment by KillerWolf1805** [comment]
Thanks for fixing it so fast

Sent from my iPhone

On 29 Jul 2020, at 01:40, Finn Thompson <notifications@github.com<mailto:notifications@github.com>> wrote:


v1.0.4 is live on the Chrome web store. Thanks again!
