### ISSUE TITLE
Do not work

### ISSUE THREAD

**Issue by gc-017** [FThompson/NetflixController#2]
Says no controllers are connected. Windows 10. Xbox One Controller. Chrome. Controllers work fine in games.

**Comment by FThompson** [comment]
Hey, thanks for posting about your issue. Would you please test your controller on https://html5gamepad.com to see if gamepads work in-browser on your system?

Also, if no gamepad is detected at first, you sometimes need to press a few buttons to get the browser to detect your controller.

If problems persist, please also let me know the Chrome version you're using.

**Comment by RedSparr0w** [comment]
Can confirm this issue,
Should be solved by updating gamepad.js once https://github.com/FThompson/Gamepads.js/pull/4 is merged.

OS: `Windows 10`
Browser: `Chrome 79.0.3945.130`
Controller: `Xbox One` - _`Xbox 360 Controller (XInput STANDARD GAMEPAD)`_

**Comment by FThompson** [comment]
I've published an update for that library and for the extension (which now works in Chrome again). The extension is pending review but should be live soon. After you have v1.0.1, it should work again.

Thanks @RedSparr0w for making this fix in Gamepads.js.

**Comment by FThompson** [comment]
v1.0.1 is live on the Chrome Web Store.
