### ISSUE TITLE
Error "cannot read dispatchEvent of null"

### ISSUE THREAD

**Issue by matas30rubliu** [FThompson/NetflixController#3]
Hello, I just checked your chrome extension - it's cool!

I just found one issue regarding localization. In my case, when you go down to section "Top 10 in Lithuania Today" it throws an error and controller stops working. If you then select with mouse any other section, which extension can recognize, controller starts working again.

I tried with both xbox360 and ps4 controllers, both times reproduced.
Attaching screenshot:
![image](https://user-images.githubusercontent.com/24503990/77190846-a57ff100-6ae2-11ea-8fd6-2e390a519beb.png)

I think I could try to contribute for fixing if you don't mind. Please take a look and let me know.

**Comment by FThompson** [comment]
Hey, thanks for reporting this issue. I checked Netflix (USA) and I have this new type of slider as well, so looks like it's a common issue regardless of locale.

I'm taking a look at how this new element works now--from a quick glance I think it should be an easy fix.
