### ISSUE TITLE
Errors when attempting navigation on the selection screen

### ISSUE THREAD

**Issue by Elzahn** [FThompson/NetflixController#8]
Error "Invalid value used as weak map key." appears when moving the left analogue stick either up or down while on the netflix browse screen. (The same error appears for most keys while on the browse screen)
Error "Cannot read "right" of undefined" appears when moving the left analogue stick right on the netflix browse screen.
Error "Cannot read "left" of undefined" appears when moving the left analogue stick left while on the netflix browse screen.

**Comment by FThompson** [comment]
Hey, thanks for reporting this--it looks like Netflix updated the UI for an element and this causes the issue. I'm looking into it now.

**Comment by FThompson** [comment]
This issue is fixed in v1.0.3, which I submitted to the Chrome Web Store for review. The update should be available soon but may take longer than usual due to COVID-19.

I'll comment again when the new version is available.

**Comment by Elzahn** [comment]
Hey, thanks for the update. Glad it was seemingly a small fix. Great plugin by the way :)

**Comment by FThompson** [comment]
Glad you like it :)

v1.0.3 is now live on the Chrome Web Store. Thanks again!
